metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: train.json
  dataset_dir: /home/gabriel/data/lrv
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: test
  anno_path: test.json
  dataset_dir: /home/gabriel/data/lrv
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: test.json
  dataset_dir: /home/gabriel/data/lrv